# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install System Dependencies
          command: sudo apt-get update && sudo apt-get install -y openmpi-bin libopenmpi-dev build-essential cython

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install numpy cython

      - run:
          name: install enspara
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[dev]

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run main tests
          command: |
            . venv/bin/activate
            nosetests -a '!mpi' enspara

      - run:
          name: run MPI tests
          command: |
            . venv/bin/activate
            mpiexec -n 2 nosetests -a mpi enspara

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
